version: '3.8'

services:

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    # command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
    #bind mount volume
      - ./backend:/usr/src/app
      - staticfiles:/usr/src/app/staticfiles
    ports:
      - 8000:8000


  nextjs:
    stdin_open: true
    build:
      context: ./nextjs

    volumes:

      - ./nextjs/src:/app/src
      - ./nextjs/public:/app/public
    ports:
      - 3000:3000

    environment:
      # - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      # - NODE_ENV=development
    depends_on:
      - backend






volumes:
  staticfiles:
